# Generated by Django 6.0.7 on 2026-08-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الخدمة')),
                ('description', models.TextField(verbose_name='وصف الخدمة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('doctor_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='الطبيب المختص')),
                ('available_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='أوقات العمل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
        ),
    ]
