# Generated by Django 6.0.7 on 2026-08-24 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=150, verbose_name='التخصص الطبي')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='التقييم')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='عدد التقييمات')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='سنوات الخبرة')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='العمر')),
                ('degree', models.CharField(blank=True, max_length=250, verbose_name='المؤهل العلمي')),
                ('schedule', models.CharField(blank=True, max_length=150, verbose_name='مواعيد الدوام')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='موقع العيادة')),
                ('available', models.BooleanField(default=True, verbose_name='متاح للحجز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('services', models.ManyToManyField(blank=True, related_name='doctors', to='services.service', verbose_name='الخدمات التي يقدمها الطبيب')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب الطبيب')),
            ],
        ),
    ]
